## Тема: Матрицы и матричные операции

In [3]:
import numpy as np

**Часть 1**

### 1. Установить, какие произведения матриц $AB$ и $BA$ определены, и найти размерности полученных матриц:

   **а)** $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$;
   
**Решение**
   
произведение матрицы $AB$ не определено, т.к. число столбцов матрицы $A$ не равно числу строк матрицы $B$  
произведение матрицы $BA$ не определено, т.к. число столбцов матрицы $A$ не равно числу строк матрицы $B$
    
   **б)** $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$;
   
**Решение**
   
произведение матрицы $AB$ определено, размерность матрицы 2 х 3  
произведение матрицы $BA$ не определено, т.к. число столбцов матрицы $A$ не равно числу строк матрицы $B$

In [105]:
Ab = np.ones((2, 5))
Bb = np.ones((5, 3))
print(f'б) Размермость произведения матриц: A(2х5) и B(5х3) = {np.shape(Ab @ Bb)}')

б) Размермость произведения матриц: A(2х5) и B(5х3) = (2, 3)


   **в)** $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$;
   
**Решение**
   
произведение матрицы $AB$ определено, размерность матрицы 8 х 8  
произведение матрицы $BA$ определено, размерность матрицы 3 х 3 

In [106]:
Av = np.ones((8, 3))
Bv = np.ones((3, 8))
print(f'в) Размермость произведения матриц: A(8х3) и B(3х8) = {np.shape(Av @ Bv)}; B(3х8) и A(8х3) = {np.shape(Bv @ Av)}')

в) Размермость произведения матриц: A(8х3) и B(3х8) = (8, 8); B(3х8) и A(8х3) = (3, 3)


   **г)** $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$.
   
**Решение**
   
произведение матрицы $AB$ определено, размерность матрицы 4 х 4   
произведение матрицы $BA$ определено, размерность матрицы 4 х 4 

In [107]:
Ag = np.ones((4, 4))
Bg = np.ones((4, 4))

print(f'г) Размермость произведения матриц: A(8х3) и B(3х8) = {np.shape(Ag @ Bg)}; B(3х8) и A(8х3) = {np.shape(Bg @ Ag)}')

г) Размермость произведения матриц: A(8х3) и B(3х8) = (4, 4); B(3х8) и A(8х3) = (4, 4)


### 2. Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

**Решение**

A + B = $\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ + 
$\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}$ = 
$\begin{pmatrix}
1 + 4 & -2 - 1\\ 
3 + 0 & 0 + 5
\end{pmatrix}$=
$\begin{pmatrix}
5 & -3\\ 
3 & 5
\end{pmatrix}$


A * B = $\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ * 
$\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}$ = 
$\begin{pmatrix}
(1*4 + (-2)*0) & (1*(-1) + (-2)*5)\\ 
(3*4 + 0*0) & (3*(-1) + 0*5)
\end{pmatrix}$ =
$\begin{pmatrix}
4 & -11\\ 
12 & -3
\end{pmatrix}$  

B * A  =
$\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}$ * 
$\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ =
$\begin{pmatrix}
1 & -8\\ 
15 & 0
\end{pmatrix}$

In [44]:
A = np.array([[1, -2],[3, 0]])
B = np.array([[4, -1],[0, 5]])
C = A + B
C

array([[ 5, -3],
       [ 3,  5]])

In [45]:
AB = A @ B
AB

array([[  4, -11],
       [ 12,  -3]])

In [46]:
BA = B @ A
BA

array([[ 1, -8],
       [15,  0]])

### 3. Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$

**Решение**

$3A-2B+4C$ = $3*\begin{pmatrix}1 & 7\\ 3 & -6\end{pmatrix}$ - $2*\begin{pmatrix}0 & 5\\ 2 & -1\end{pmatrix}$ + $4*\begin{pmatrix}2 & -4\\ 1 & 1\end{pmatrix}$ = $\begin{pmatrix}3 & 21\\ 9 & -18\end{pmatrix}$ - $\begin{pmatrix}0 & 10\\ 4 & -2\end{pmatrix}$ + $\begin{pmatrix}8 & -16\\ 4 & 4\end{pmatrix}$ = $\begin{pmatrix}11 & -5\\ 9 & -12\end{pmatrix}$

In [31]:
A = np.array([[1, 7],[3, -6]])
B = np.array([[0, 5],[2, -1]])
C = np.array([[2, -4],[1, 1]])

print(3*A - 2*B + 4*C)

[[ 11  -5]
 [  9 -12]]


### 4. Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$. Вычислить $AA^{T}$ и $A^{T}A$.

**Решение**

In [34]:
A = np.array([[4, 1],[5, -2],[2, 3]])
AT = A.T
AT

array([[ 4,  5,  2],
       [ 1, -2,  3]])

In [35]:
B = A @ AT
B

array([[17, 18, 11],
       [18, 29,  4],
       [11,  4, 13]])

In [36]:
B1 = AT @ A
B1

array([[45,  0],
       [ 0, 14]])

### 5*. Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

**Решение**

In [89]:
matrix1 = [[2, 5, 4], [3, 6, 8]]
matrix2 = [[1, 2], [0, 1], [8, 5]]

matrix3 = [[0 for x in range(len(matrix1))] for y in range(len(matrix1))] 

for i in range(len(matrix1)):
    for j in range(len(matrix2[0])):
        for k in range(len(matrix2)):
            matrix3[i][j] += matrix1[i][k] * matrix2[k][j]
        
print(matrix3)

[[34, 29], [67, 52]]


**Часть 1**

### 1. Вычислить определитель:

   **a)**$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix}$

**Решение**

$sin^2x + cos^2x = 1$

In [130]:
x = 15
A = np.array([[np.sin(x), -np.cos(x)], [np.cos(x), np.sin(x)]])
np.linalg.det(A)

1.0

   **б)**$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix}$

**Решение**

$4\cdot\begin{vmatrix}
5 & 1\\ 
0 & 9
\end{vmatrix}-
2\cdot\begin{vmatrix}
0 & 1\\ 
0 & 9
\end{vmatrix}+
3\cdot\begin{vmatrix}
0 & 5\\ 
0 & 0
\end{vmatrix}=4\cdot(5\cdot9-1\cdot0)-2\cdot(0\cdot9-1\cdot0)+3\cdot(0\cdot0-5\cdot0) = 180 - 0 + 0 = 180$
    

In [92]:
B = np.array([[4, 2, 3], [0, 5, 1], [0, 0, 9]])
np.linalg.det(B)

180.0

**в)**$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}$

**Решение**

$1\cdot\begin{vmatrix}
5 & 6\\ 
8 & 9
\end{vmatrix}-
2\cdot\begin{vmatrix}
4 & 6\\ 
7 & 9
\end{vmatrix}+
3\cdot\begin{vmatrix}
4 & 5\\ 
7 & 8
\end{vmatrix}=1\cdot(5\cdot9-6\cdot8)-2\cdot(4\cdot9-6\cdot7)+3\cdot(4\cdot8-5\cdot7)= -3 + 12 - 9 = 0$

In [103]:
V = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
np.round(np.linalg.det(V))

-0.0

### 2. Определитель матрицы $A$ равен $4$. Найти:

In [131]:
A = np.array([[1, 2, 1], [0, 2, 1], [0, 0, 2]])
np.linalg.det(A)

4.0

**а)** $det(A^{2})$;

$4^2 = 16$

In [132]:
np.round(np.linalg.det(A @ A))

16.0

  **б)** $det(A^{T})$;  
4

In [133]:
np.round(np.linalg.det(A.T))

4.0

**в)** $det(2A)$.  
2 * 4 = 8

In [134]:
np.round(np.linalg.det(2*A)) #???

32.0

### 3.  Доказать, что матрица $\begin{pmatrix}-2 & 7 & -3\\ 4 & -14 & 6\\ -3 & 7 & 13\end{pmatrix}$ вырожденная.

**Решение**

$-2\cdot\begin{vmatrix}
-14 & 6\\ 
7 & 13
\end{vmatrix}-
7\cdot\begin{vmatrix}
4 & 6\\ 
-3 & 13
\end{vmatrix}-
3\cdot\begin{vmatrix}
4 & -14\\ 
-3 & 7
\end{vmatrix}=-2\cdot(-14\cdot13-6\cdot7)-7\cdot(4\cdot13-6\cdot-3)-3\cdot(4\cdot7-(-14)\cdot-3)= 448 - 490 + 42 = 0$

In [104]:
A = np.array([[-2, 7, -3], [4, -14, 6], [-3, 7, 13]])
np.round(np.linalg.det(A))

0.0

### 4. Найти ранг матрицы:

   **а)** $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix}$

**Решение**

Третья строка является суммой первой и второй строк, а значит, ее можно отбросить:

$\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1
\end{pmatrix}$

Вычтем из второй строки первую:

$\begin{pmatrix}
1 & 2 & 3\\ 
0 & -1 & -2
\end{pmatrix}$

Таким образом, ранг матрицы равен 2.

In [108]:
a = np.array([[1, 2, 3], [1, 1, 1], [2, 3, 4]])
r = np.linalg.matrix_rank(a)

print(f'Ранг матрицы: {r}')

Ранг матрицы: 2


   **б)** $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}$

**Решение**

In [110]:
b = np.array([[0, 0, 2, 1], [0, 0, 2, 2], [0, 0, 4, 3], [2, 3, 5, 6]])
r = np.linalg.matrix_rank(b)

print(f'Ранг матрицы: {r}')

Ранг матрицы: 3
